name: Auto-increment Version

on:
  push:
    branches: [ main ]
    paths:
      - 'note2self.json'
      - '.github/workflows/request_payload.json'

jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment version
        run: |
          jq '.note.timestamp |= . + 1' note2self.json > temp.json && mv temp.json note2self.json
          jq '.note.timestamp |= . + 1' .github/workflows/request_payload.json > temp.json && mv temp.json .github/workflows/request_payload.json
          
      - name: Ensure newline at end of files
        run: |
          sed -i -e '$a\' note2self.json
          sed -i -e '$a\' .github/workflows/request_payload.json
          
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add note2self.json .github/workflows/request_payload.json
          git commit -m "Auto-increment version [skip ci]"
          git push

  ai-recommendations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate AI recommendations
        run: python ai_recommendations.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add ai_recommendations.json
          git commit -m 'Update AI recommendations'
          git push origin HEAD:main
